# Generated by Django 5.1.4 on 2026-03-26 20:16

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('localization', '0002_alter_commune_options_alter_wilaya_options_and_more'),
        ('products', '0003_productimage_alter_category_options_and_more'),
        ('services', '0004_alter_service_created_at_alter_service_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='الاسم الأول')),
                ('last_name', models.CharField(max_length=50, verbose_name='اسم العائلة')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='البريد الإلكتروني')),
                ('phone_number', models.CharField(help_text='رقم هاتف جزائري مكوّن من 10 أرقام.', max_length=10, validators=[django.core.validators.RegexValidator(message='أدخل رقم هاتف جزائري صالح (مثال: 0551234567).', regex='^(0)(5|6|7)\\d{8}$')], verbose_name='رقم الهاتف')),
                ('address', models.TextField(help_text='رقم العمارة، الشارع، الحي... إلخ.', verbose_name='العنوان بالتفصيل')),
                ('total_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='بالدينار الجزائري (DZD).', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='المبلغ الإجمالي')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('confirmed', 'مؤكّد'), ('shipped', 'تم الشحن'), ('delivered', 'تم التوصيل'), ('cancelled', 'ملغى')], db_index=True, default='pending', max_length=20, verbose_name='حالة الطلب')),
                ('payment_method', models.CharField(choices=[('cod', 'الدفع عند الاستلام'), ('cib', 'بطاقة CIB'), ('edahabia', 'بطاقة الذهبية')], default='cod', max_length=20, verbose_name='طريقة الدفع')),
                ('is_paid', models.BooleanField(default=False, verbose_name='تم الدفع؟')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ آخر تعديل')),
                ('commune', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='localization.commune', verbose_name='البلدية')),
                ('user', models.ForeignKey(blank=True, help_text='يُترك فارغاً إذا كان الطلب من زائر.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
                ('wilaya', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='localization.wilaya', verbose_name='الولاية')),
            ],
            options={
                'verbose_name': 'طلب',
                'verbose_name_plural': 'الطلبات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, help_text='سعر الوحدة بالدينار الجزائري وقت إتمام الطلب.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='السعر عند الشراء')),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='الكمية')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='الطلب')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='products.product', verbose_name='المنتج')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='services.service', verbose_name='الخدمة')),
            ],
            options={
                'verbose_name': 'عنصر طلب',
                'verbose_name_plural': 'عناصر الطلب',
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['-created_at'], name='idx_order_created'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='idx_order_status'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', 'status'], name='idx_order_user_status'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(('product__isnull', False), ('service__isnull', False), _connector='OR'), name='orderitem_must_have_product_or_service'),
        ),
    ]
