# Generated by Django 5.1.4 on 2026-03-26 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('localization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نوع الخدمة')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان الخدمة')),
                ('description', models.TextField(verbose_name='تفاصيل الخدمة')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر')),
                ('is_available', models.BooleanField(default=True, verbose_name='متاح حالياً')),
                ('coverage_area', models.ManyToManyField(to='localization.wilaya', verbose_name='منطقة التغطية')),
            ],
        ),
    ]
