# Generated by Django 5.1.4 on 2026-03-26 15:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localization', '0001_initial'),
        ('services', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['-created_at'], 'verbose_name': 'خدمة', 'verbose_name_plural': 'الخدمات'},
        ),
        migrations.AlterModelOptions(
            name='servicecategory',
            options={'verbose_name': 'تصنيف الخدمة', 'verbose_name_plural': 'تصنيفات الخدمات'},
        ),
        migrations.RemoveField(
            model_name='service',
            name='coverage_area',
        ),
        migrations.RemoveField(
            model_name='service',
            name='is_available',
        ),
        migrations.RemoveField(
            model_name='service',
            name='title',
        ),
        migrations.AddField(
            model_name='service',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AddField(
            model_name='service',
            name='duration_hours',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='المدة التقريبية (بالساعات)'),
        ),
        migrations.AddField(
            model_name='service',
            name='image_main',
            field=models.ImageField(blank=True, null=True, upload_to='services/images/', verbose_name='صورة الخدمة'),
        ),
        migrations.AddField(
            model_name='service',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='نشط'),
        ),
        migrations.AddField(
            model_name='service',
            name='name',
            field=models.CharField(default='', max_length=200, verbose_name='اسم الخدمة'),
        ),
        migrations.AddField(
            model_name='service',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='آخر تحديث'),
        ),
        migrations.AddField(
            model_name='service',
            name='wilayas',
            field=models.ManyToManyField(blank=True, to='localization.wilaya', verbose_name='مناطق التغطية (الولايات)'),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True, verbose_name='الرابط اللطيف'),
        ),
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='services.servicecategory', verbose_name='التصنيف'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(verbose_name='وصف الخدمة'),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر (دج)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to=settings.AUTH_USER_MODEL, verbose_name='مقدم الخدمة'),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='اسم التصنيف'),
        ),
    ]
