# Generated by Django 5.1.4 on 2026-03-28 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_rename_provider_to_vendor'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='services/gallery/', verbose_name='الصورة')),
                ('alt_text', models.CharField(blank=True, default='', max_length=200, verbose_name='النص البديل (Alt)')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='الترتيب')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='services.service', verbose_name='الخدمة')),
            ],
            options={
                'verbose_name': 'صورة الخدمة',
                'verbose_name_plural': 'صور الخدمات',
                'ordering': ['order', 'id'],
            },
        ),
    ]
