# Generated by Django 5.1.4 on 2026-03-26 11:27

import apps.users.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localization', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-date_joined'], 'verbose_name': 'مستخدم', 'verbose_name_plural': 'المستخدمون'},
        ),
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='يصبح True بعد التحقق من رقم الهاتف أو البريد الإلكتروني', verbose_name='حساب موثّق'),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=apps.users.models.user_profile_picture_path, verbose_name='صورة الملف الشخصي'),
        ),
        migrations.AddField(
            model_name='user',
            name='wilaya',
            field=models.ForeignKey(blank=True, help_text='الولاية الجزائرية، تُستخدم لحساب رسوم ومدة التوصيل', null=True, on_delete=django.db.models.deletion.SET_NULL, to='localization.wilaya', verbose_name='الولاية'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default='0000000000', help_text='رقم هاتف جزائري فعّال. مثال: 0661234567', max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='رقم الهاتف غير صحيح. يجب أن يبدأ بـ 05 أو 06 أو 07 (أو +2135 / +2136 / +2137). مثال: 0661234567', regex='^(\\+213|0)(5|6|7)\\d{8}$')], verbose_name='رقم الهاتف'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CUSTOMER', 'عميل'), ('SELLER', 'بائع'), ('PROVIDER', 'مقدم خدمة')], db_index=True, default='CUSTOMER', max_length=10, verbose_name='الدور'),
        ),
    ]
