# Generated by Django 5.1.4 on 2026-03-28 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_options_user_is_verified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CUSTOMER', 'عميل'), ('SELLER', 'بائع'), ('PROVIDER', 'مقدم خدمة'), ('INSTITUTION', 'مؤسسة')], db_index=True, default='CUSTOMER', max_length=20, verbose_name='الدور'),
        ),
    ]
