# Generated by Django 5.1.4 on 2026-03-28 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='university_name',
            field=models.CharField(blank=True, help_text='الجامعة التابعة لها الحاضنة', max_length=255, null=True, verbose_name='اسم الجامعة'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CUSTOMER', 'عميل'), ('VENDOR', 'بائع/مقدم خدمة'), ('INSTITUTION', 'مؤسسة'), ('INCUBATOR', 'حاضنة جامعية')], db_index=True, default='CUSTOMER', max_length=20, verbose_name='الدور'),
        ),
    ]
