# Generated by Django 5.1.4 on 2026-03-28 17:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_university_name_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='incubator',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'INCUBATOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incubated_institutions', to=settings.AUTH_USER_MODEL, verbose_name='الحاضنة الوصية'),
        ),
        migrations.AddField(
            model_name='user',
            name='performance_score',
            field=models.PositiveIntegerField(default=0, help_text='درجة تقييم أداء المؤسسة من 0 إلى 100', verbose_name='درجة الأداء'),
        ),
        migrations.CreateModel(
            name='IncubatorMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='الاسم الكامل')),
                ('position', models.CharField(max_length=255, verbose_name='المنصب/الدور')),
                ('image', models.ImageField(blank=True, null=True, upload_to='incubators/team/', verbose_name='الصورة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('incubator', models.ForeignKey(limit_choices_to={'role': 'INCUBATOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'عضو فريق حاضنة',
                'verbose_name_plural': 'أعضاء فريق الحاضنة',
            },
        ),
    ]
