# Generated by Django 5.1.4 on 2026-03-28 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_incubator_user_performance_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incubatormember',
            name='bio',
            field=models.TextField(blank=True, null=True, verbose_name='نبذة مختصرة'),
        ),
        migrations.AddField(
            model_name='incubatormember',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='البريد الإلكتروني'),
        ),
        migrations.AddField(
            model_name='incubatormember',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم الهاتف'),
        ),
    ]
