# Generated by Django 5.1.4 on 2026-03-29 11:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_incubatormember_bio_incubatormember_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='الاسم الكامل')),
                ('position', models.CharField(max_length=255, verbose_name='المنصب/الدور')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='البريد الإلكتروني')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم الهاتف')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='نبذة مختصرة')),
                ('image', models.ImageField(blank=True, null=True, upload_to='teams/members/', verbose_name='الصورة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(help_text='المستخدم (الحاضنة أو المؤسسة) الذي ينتمي إليه هذا العضو', on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'عضو فريق',
                'verbose_name_plural': 'أعضاء الفريق',
            },
        ),
        migrations.DeleteModel(
            name='IncubatorMember',
        ),
    ]
