# Generated by Django 5.1.4 on 2026-03-26 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localization', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commune',
            options={'ordering': ['name'], 'verbose_name': 'بلدية', 'verbose_name_plural': 'البلديات'},
        ),
        migrations.AlterModelOptions(
            name='wilaya',
            options={'ordering': ['code'], 'verbose_name': 'ولاية', 'verbose_name_plural': 'الولايات'},
        ),
        migrations.AlterField(
            model_name='commune',
            name='name',
            field=models.CharField(max_length=50, verbose_name='اسم البلدية'),
        ),
        migrations.AlterField(
            model_name='commune',
            name='wilaya',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communes', to='localization.wilaya', verbose_name='الولاية'),
        ),
        migrations.AlterField(
            model_name='wilaya',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='اسم الولاية'),
        ),
        migrations.AlterField(
            model_name='wilaya',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='تكلفة التوصيل (دج)'),
        ),
    ]
