# Generated by Django 5.1.4 on 2026-03-28 09:59

import apps.vendors.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localization', '0002_alter_commune_options_alter_wilaya_options_and_more'),
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='store',
            options={'verbose_name': 'متجر', 'verbose_name_plural': 'المتاجر'},
        ),
        migrations.AddField(
            model_name='store',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to=apps.vendors.models.store_banner_path, verbose_name='بانر المتجر'),
        ),
        migrations.AddField(
            model_name='store',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='متجر موثّق'),
        ),
        migrations.AddField(
            model_name='store',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=apps.vendors.models.store_logo_path, verbose_name='الشعار'),
        ),
        migrations.AddField(
            model_name='store',
            name='phone',
            field=models.CharField(blank=True, max_length=15, verbose_name='رقم الهاتف'),
        ),
        migrations.AddField(
            model_name='store',
            name='return_policy',
            field=models.TextField(blank=True, verbose_name='سياسة الإرجاع'),
        ),
        migrations.AddField(
            model_name='store',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='store',
            name='wilaya',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='localization.wilaya', verbose_name='الولاية'),
        ),
    ]
