# Generated by Django 5.1.4 on 2026-03-28 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_alter_store_options_store_banner_store_is_verified_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم المؤسسة')),
                ('sector', models.CharField(max_length=255, verbose_name='المجال')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('approved', 'مقبول'), ('rejected', 'مرفوض')], default='pending', max_length=20, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الطلب')),
            ],
            options={
                'verbose_name': 'طلب انضمام مؤسسة',
                'verbose_name_plural': 'طلبات انضمام المؤسسات',
                'ordering': ['-created_at'],
            },
        ),
    ]
