# Generated by Django 5.1.4 on 2026-03-28 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0004_organizationrequest_incubator'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='location_detail',
            field=models.CharField(blank=True, max_length=255, verbose_name='الموقع داخل الحرم'),
        ),
        migrations.AddField(
            model_name='store',
            name='manager_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='اسم مدير الحاضنة'),
        ),
    ]
