# Generated by Django 5.1.4 on 2026-04-04 08:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0005_store_location_detail_store_manager_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='رمز الكوبون')),
                ('type', models.CharField(choices=[('percentage', 'نسبة مئوية %'), ('fixed', 'مبلغ ثابت د.ج')], default='percentage', max_length=20, verbose_name='نوع الخصم')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='القيمة')),
                ('min_order', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='الحد الأدنى للطلب')),
                ('max_uses', models.PositiveIntegerField(default=100, verbose_name='الحد الأقصى للاستخدامات')),
                ('used', models.PositiveIntegerField(default=0, verbose_name='مرات الاستخدام')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('expires_at', models.DateField(verbose_name='تاريخ الانتهاء')),
                ('applies_to', models.CharField(choices=[('all', 'الكل'), ('products', 'المنتجات فقط'), ('services', 'الخدمات فقط')], default='all', max_length=20, verbose_name='يُطبق على')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to=settings.AUTH_USER_MODEL, verbose_name='التاجر')),
            ],
            options={
                'verbose_name': 'كوبون',
                'verbose_name_plural': 'الكوبونات',
                'ordering': ['-created_at'],
            },
        ),
    ]
