# Generated by Django 5.1.4 on 2026-03-26 21:10

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0003_productimage_alter_category_options_and_more'),
        ('services', '0004_alter_service_created_at_alter_service_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(help_text='من 1 إلى 5 نجوم', validators=[django.core.validators.MinValueValidator(1, message='أقل تقييم ممكن هو نجمة واحدة.'), django.core.validators.MaxValueValidator(5, message='أعلى تقييم ممكن هو 5 نجوم.')], verbose_name='التقييم')),
                ('comment', models.TextField(help_text='اكتب مراجعتك هنا', verbose_name='التعليق')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='products.product', verbose_name='المنتج')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='services.service', verbose_name='الخدمة')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'تقييم',
                'verbose_name_plural': 'التقييمات',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('product__isnull', False)), fields=('user', 'product'), name='unique_user_product_review'), models.UniqueConstraint(condition=models.Q(('service__isnull', False)), fields=('user', 'service'), name='unique_user_service_review'), models.CheckConstraint(condition=models.Q(models.Q(('product__isnull', False), ('service__isnull', True)), models.Q(('product__isnull', True), ('service__isnull', False)), _connector='OR'), name='review_linked_to_product_xor_service')],
            },
        ),
    ]
